version: '3'

services:
  web:
    build: .
    container_name: web
    volumes:
      - .:/usr/src/Desktop/weather_watch
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TOKEN
    command:
      sh -c "python3 manage.py makemigrations && 
      python3 manage.py migrate && 
      python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null